package com.clouderwork.innoz.domain;

public class Service {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_service.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_service.svc_name
     *
     * @mbggenerated
     */
    private String svcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_service.svc_version
     *
     * @mbggenerated
     */
    private String svcVersion;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_service.provider_id
     *
     * @mbggenerated
     */
    private Integer providerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_service.svc_desc
     *
     * @mbggenerated
     */
    private String svcDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_service.svc_type
     *
     * @mbggenerated
     */
    private String svcType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_service.id
     *
     * @return the value of sv_service.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_service.id
     *
     * @param id the value for sv_service.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_service.svc_name
     *
     * @return the value of sv_service.svc_name
     *
     * @mbggenerated
     */
    public String getSvcName() {
        return svcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_service.svc_name
     *
     * @param svcName the value for sv_service.svc_name
     *
     * @mbggenerated
     */
    public void setSvcName(String svcName) {
        this.svcName = svcName == null ? null : svcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_service.svc_version
     *
     * @return the value of sv_service.svc_version
     *
     * @mbggenerated
     */
    public String getSvcVersion() {
        return svcVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_service.svc_version
     *
     * @param svcVersion the value for sv_service.svc_version
     *
     * @mbggenerated
     */
    public void setSvcVersion(String svcVersion) {
        this.svcVersion = svcVersion == null ? null : svcVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_service.provider_id
     *
     * @return the value of sv_service.provider_id
     *
     * @mbggenerated
     */
    public Integer getProviderId() {
        return providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_service.provider_id
     *
     * @param providerId the value for sv_service.provider_id
     *
     * @mbggenerated
     */
    public void setProviderId(Integer providerId) {
        this.providerId = providerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_service.svc_desc
     *
     * @return the value of sv_service.svc_desc
     *
     * @mbggenerated
     */
    public String getSvcDesc() {
        return svcDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_service.svc_desc
     *
     * @param svcDesc the value for sv_service.svc_desc
     *
     * @mbggenerated
     */
    public void setSvcDesc(String svcDesc) {
        this.svcDesc = svcDesc == null ? null : svcDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_service.svc_type
     *
     * @return the value of sv_service.svc_type
     *
     * @mbggenerated
     */
    public String getSvcType() {
        return svcType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_service.svc_type
     *
     * @param svcType the value for sv_service.svc_type
     *
     * @mbggenerated
     */
    public void setSvcType(String svcType) {
        this.svcType = svcType == null ? null : svcType.trim();
    }
}