package com.clouderwork.innoz.domain;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_user.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_user.user_name
     *
     * @mbggenerated
     */
    @NotNull
    @Size(min=2, max=30)
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_user.password
     *
     * @mbggenerated
     */
    @NotNull
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_user.phone_no
     *
     * @mbggenerated
     */
    private String phoneNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_user.register_date
     *
     * @mbggenerated
     */
    private Date registerDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_user.user_level
     *
     * @mbggenerated
     */
    private Integer userLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sv_user.user_type
     *
     * @mbggenerated
     */
    private Integer userType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_user.id
     *
     * @return the value of sv_user.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_user.id
     *
     * @param id the value for sv_user.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_user.user_name
     *
     * @return the value of sv_user.user_name
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_user.user_name
     *
     * @param userName the value for sv_user.user_name
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_user.password
     *
     * @return the value of sv_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_user.password
     *
     * @param password the value for sv_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_user.email
     *
     * @return the value of sv_user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_user.email
     *
     * @param email the value for sv_user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_user.phone_no
     *
     * @return the value of sv_user.phone_no
     *
     * @mbggenerated
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_user.phone_no
     *
     * @param phoneNo the value for sv_user.phone_no
     *
     * @mbggenerated
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_user.register_date
     *
     * @return the value of sv_user.register_date
     *
     * @mbggenerated
     */
    public Date getRegisterDate() {
        return registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_user.register_date
     *
     * @param registerDate the value for sv_user.register_date
     *
     * @mbggenerated
     */
    public void setRegisterDate(Date registerDate) {
        this.registerDate = registerDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_user.user_level
     *
     * @return the value of sv_user.user_level
     *
     * @mbggenerated
     */
    public Integer getUserLevel() {
        return userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_user.user_level
     *
     * @param userLevel the value for sv_user.user_level
     *
     * @mbggenerated
     */
    public void setUserLevel(Integer userLevel) {
        this.userLevel = userLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sv_user.user_type
     *
     * @return the value of sv_user.user_type
     *
     * @mbggenerated
     */
    public Integer getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sv_user.user_type
     *
     * @param userType the value for sv_user.user_type
     *
     * @mbggenerated
     */
    public void setUserType(Integer userType) {
        this.userType = userType;
    }
}